<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WarlordUpdater\Module'                                  => __DIR__ . '/Module.php',
    'WarlordUpdater\Controller\Plugin\BasePlugin'            => __DIR__ . '/src/WarlordUpdater/Controller/Plugin/BasePlugin.php',
    'WarlordUpdater\Controller\Plugin\InstallPlugin'         => __DIR__ . '/src/WarlordUpdater/Controller/Plugin/InstallPlugin.php',
    'WarlordUpdater\Controller\Plugin\LoadDirPlugin'         => __DIR__ . '/src/WarlordUpdater/Controller/Plugin/LoadDirPlugin.php',
    'WarlordUpdater\Controller\Plugin\UpdatePlugin'          => __DIR__ . '/src/WarlordUpdater/Controller/Plugin/UpdatePlugin.php',
    'WarlordUpdater\Controller\UpdaterController'            => __DIR__ . '/src/WarlordUpdater/Controller/UpdaterController.php',
    'WarlordUpdater\Model\Update'                            => __DIR__ . '/src/WarlordUpdater/Model/Update.php',
    'WarlordUpdater\Model\UpdateTable'                       => __DIR__ . '/src/WarlordUpdater/Model/UpdateTable.php',
    'WarlordUpdaterTest\Bootstrap'                           => __DIR__ . '/test/Bootstrap.php',
    'WarlordUpdaterTest\Controller\Plugin\InstallPluginTest' => __DIR__ . '/test/WarlordUpdaterTest/Controller/Plugin/InstallPluginTest.php',
    'WarlordUpdaterTest\Controller\Plugin\UpdatePluginTest'  => __DIR__ . '/test/WarlordUpdaterTest/Controller/Plugin/UpdatePluginTest.php',
    'WarlordUpdaterTest\Controller\UpdaterControllerTest'    => __DIR__ . '/test/WarlordUpdaterTest/Controller/UpdaterControllerTest.php',
    'WarlordUpdaterTest\Framework\TestCase'                  => __DIR__ . '/test/WarlordUpdaterTest/Framework/TestCase.php',
);
